### ISSUE TITLE
Interpretation of Dex component

### ISSUE THREAD

**Issue by andrewram4287** [meyer-lab/scCP#314]
Determine which cells Dex HCl is picking out and whether they are identifying a subset of an overall subtype; previous investigation of raw data does not show apparent difference with respect to the genes picked out by that component

**Comment by aarmey** [comment]
@andrewram4287 check what the factors look like after read depth normalization (on `main`). It seems to me that the other drug effects remain but Dec disappeared. It's possible it had to do with some read depth difference overall?

**Comment by andrewram4287** [comment]
@aarmey I would say more than just the Dex HCl component is removed, even when adding more components, the drug-specific patterns are not picked up anymore. I believe you are right that the read depth definitely changes since Pf2 is most likely picking up those few cells with high read counts .
<img width="550" alt="Screenshot 2023-11-21 at 8 47 02 AM" src="https://github.com/meyer-lab/scCP/assets/91349614/19535b73-a6f9-48e3-a0cc-19970fb18210">
<img width="543" alt="Screenshot 2023-11-21 at 8 47 07 AM" src="https://github.com/meyer-lab/scCP/assets/91349614/2b1b3023-fd1a-414d-aad1-6a39417ad89c">
<img width="1168" alt="Screenshot 2023-11-21 at 8 47 33 AM" src="https://github.com/meyer-lab/scCP/assets/91349614/5a0e814f-0665-47e0-99e3-b670d673d0bc">
<img width="1440" alt="Screenshot 2023-11-21 at 8 47 52 AM" src="https://github.com/meyer-lab/scCP/assets/91349614/80b0e876-b74d-4fed-81a6-17fb7a845b82">

**Comment by aarmey** [comment]
@andrewram4287 is there a drug-specific effect you could see in the raw data, that you don't see reflected here? The glucocorticoids are definitely present. Alprostadil has a specific component. The mTOR drugs look to be cmp. 14 in the 30-cmp model. I agree that the results shifted quite a bit, more than I expected. However, to the extent the results change, I think that makes an argument *for* this normalization. I also want to have a good argument either way, beyond what looks familiar to us...

**Comment by andrewram4287** [comment]
@aarmey After investigating the previous other components that were drug-specific, and investigating the highly weighted genes for that component, the average raw gene expression is not extremely different than other drug perturbations (This is the case for both normalizing based on read depth and using our original normalization). I assume that the cells with large read counts is what is being picked out when we use Pf2, but when we normalize based on read depth, we remove that variation

**Comment by aarmey** [comment]
Not sure I’m following. Are you talking about Dex specifically?

**Comment by andrewram4287** [comment]
@aarmey I was investigating the old Pf2 factorization results that picked out the drugs of Cyclosporine, CTRL6, and Latrepirdine 2HCl. I investigated the genes for that was picked out for these drug specific components, to see if there was a large difference in the raw gene count. I investigated these gene expression using our new read depth normalization, and without the normalization. I currently don't see clear differences with respect to the drugs picked out versus other drugs.

**Comment by aarmey** [comment]
Ok! It sounds like this issue is effectively resolved, then? If so, you can close.

**Comment by andrewram4287** [comment]
@aarmey Does this mean we won't be discussing the former normalization anymore? The story of the paper will change since we won't be able to discuss a component that highlights Dex Hcl. It might make more sense to talk about Alprostadil since that drug might have cleaner separation when looking back at the genes
