### ISSUE TITLE
Move lupus factorization to the raw/full data

### ISSUE THREAD

**Issue by andrewram4287** [meyer-lab/scCP#316]
Normalization issue that results in the R2X to be extremely high; for a rank 1 Pf2 model, R2X is about 0.4; I have determined which genes are picked out, need to determine which genes would be best to remove for this case. Genes picked are mostly ribosomal/mitochondrial genes, along with MALAT1

**Comment by aarmey** [comment]
Normalizing read depth does seem to resolve this issue. However, it looks like there are still batch effects in the data. We might just have to go with the batch correction from the authors, because heavy batch correction methods would be very involved...

**Comment by aarmey** [comment]
We could still use the factorization from the batch correction data, but look back at the raw genes when looking at what is different among groups of cells.

**Comment by aarmey** [comment]
Let's go with our existing factorization. We can come back to this after posting the paper, but I think there is a path to getting the paper out that doesn't require the full dataset.

**Comment by aarmey** [comment]
Fixed!
